image: wcr.io/odxsre/k8s-terraform-ansible-gitlab:0.1

stages:
  - integ

variables:
  ENV_NAME: gitlab-ci
  REGION: us-ashburn-1
  EXTERNAL_DOMAIN: gitlabci.k8s.oracledx.com
  LOG_DIR: ${CI_PROJECT_DIR}/log

.upload_artifacts: &upload_artifacts
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    when: always
    paths:
    - ${LOG_DIR}
    expire_in: 3d

.terragrunt_destroy: &terragrunt_destroy
  after_script:
    - echo "### * Destroying environment (${ENV_NAME})..."
    - envs/${ENV_NAME}/destroy.sh

deploy_from_scratch:
  before_script:
  stage: integ
  only:
    - master
    - branches
  variables:
    MASTER_SHAPE: VM.Standard1.2
    WORKER_SHAPE: VM.Standard1.2
    MASTER_AD: 2
    WORKER_AD: 3
  script:
    # Create environment
    - echo "### * Creating environment (${ENV_NAME})..."
    - export TF_VAR_private_key_path=/tmp/private.key
    - echo "$TF_VAR_private_key" > $TF_VAR_private_key_path
    - echo 'providers { baremetal = "/linux_amd64/terraform-provider-baremetal" }' > ~/.terraformrc
    - python scripts/create_env.py ${ENV_NAME} --unmanaged --logging_ad $((1 + RANDOM % 3)) --monitoring_ad $((1 + RANDOM % 3)) --shape ${MASTER_SHAPE} --region ${REGION} --tenancy_ocid $TF_VAR_tenancy_ocid --compartment_ocid $TF_VAR_compartment_ocid --user_ocid $TF_VAR_user_ocid --fingerprint $TF_VAR_fingerprint --private_key_file $TF_VAR_private_key_path --admin_user ${ENV_NAME} --admin_password ${ENV_NAME} --external_domain ${EXTERNAL_DOMAIN} --self_signed_certs
    #- python scripts/create_env.py ${ENV_NAME} --unmanaged --master_ad${MASTER_AD}_nodes 1 --worker_ad${WORKER_AD}_nodes 1 --master_shape ${MASTER_SHAPE} --worker_shape ${WORKER_SHAPE} --region ${REGION} --tenancy_ocid $TF_VAR_tenancy_ocid --compartment_ocid $TF_VAR_compartment_ocid --user_ocid $TF_VAR_user_ocid --fingerprint $TF_VAR_fingerprint --private_key_file $TF_VAR_private_key_path
    - echo "### * Successfully created ${ENV_NAME} environment!"
    # Populate environment for consumption by tests
    - python ./scripts/populate_env.py ${ENV_NAME}
    - export PYTHONPATH=`pwd`/scripts
    # Run Acceptance Tests
    - echo "### * Running Acceptance Tests..."
    - python tests/integration_tests.py envs/${ENV_NAME}/files/health.json
    - echo "### * Acceptance tests passed!"
    # Verify idempotency
    #- echo "### * Verifying idempotency..."
    #- OUTPUT=$(python ./scripts/ansible_deploy_env.py ${ENV_NAME} --force | tee /tmp/output)
    #- if egrep 'changed=[^0]' /tmp/output;then (exit 127);fi
    #- echo "### * Idempotency check passed!"
  <<: *terragrunt_destroy