---
- name: Remove unnecessary Docker service files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/systemd/system/docker.service.d

- name: Install docker unit file
  template:
    src: templates/docker.service
    dest: /etc/systemd/system/docker.service
    owner: root
    group: root
    mode: 0644
  register: docker_service

- name: Start Docker Service
  service:
     name: docker
     daemon-reload: yes
     state: restarted
     enabled: yes
  when: docker_service.changed
