---
- name: Add Kubernetes repo
  yum_repository:
    name: yum.kubernetes.io_repos_kubernetes-el7-x86_64
    description: Kubernetes repo
    baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64

- name: Import Google cloud YUM key
  rpm_key:
    state: present
    key: https://packages.cloud.google.com/yum/doc/yum-key.gpg

- name: Import Google cloud RPM key
  rpm_key:
    state: present
    key: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Install K8S base packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - kubelet
    - kubectl
    - kubernetes-cni

- name: Remove unnecessary Docker service files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/systemd/system/docker.service.d

- name: Install docker unit file
  template:
    src: templates/docker.service
    dest: /etc/systemd/system/docker.service
    owner: root
    group: root
    mode: 0644
  register: docker_service

- name: Start Docker Service
  service:
     name: docker
     daemon-reload: yes
     state: restarted
     enabled: yes
  when: docker_service.changed
