
- name: Add kubernetes repo
  yum_repository:
    name: yum.kubernetes.io_repos_kubernetes-el7-x86_64
    description: Kubernetes repo
    baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64

- name: Import google cloud YUM key
  rpm_key:
    state: present
    key: https://packages.cloud.google.com/yum/doc/yum-key.gpg

- name: Import google cloud RPM key
  rpm_key:
    state: present
    key: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - kubelet
    - kubectl
    - kubernetes-cni

# Getting k8s pod networking working with firewalld is tricky, turn it off for now
- name: Disable Firewalld
  service:
      name: firewalld
      state: stopped
      enabled:  no


- name: Remove unnecessary flannel docker config
  command: "{{ item }}"
  with_items:
      - rm -rf /usr/lib/systemd/system/docker.service.d
      - rm -f /run/flannel/docker
      - rm -rf /etc/systemd/system/docker.service.d


- name: Install docker unit file
  template:
    src: templates/docker.service
    dest: /usr/lib/systemd/system/docker.service
    owner: root
    group: root
    mode: 0644
  register: docker_svc_updated


- name: Start Docker Service
  service:
     daemon-reload: yes
     name: docker
     state: restarted
     enabled: yes

  when: docker_svc_updated

- name: Create manifests dirs
  file:
    state: directory
    path: /etc/kubernetes/manifests
    owner: root
    group: root
    mode: 0755

- name: Install k8s apiserver yaml file
  template:
    src: templates/kube-apiserver.yaml
    dest: /etc/kubernetes/manifests/kube-apiserver.yaml
    owner: root
    group: root
    mode: 0755

- name: Install k8s controller yaml file
  template:
    src: templates/kube-controller-manager.yaml
    dest: /etc/kubernetes/manifests/kube-controller-manager.yaml
    owner: root
    group: root
    mode: 0755

- name: Install k8s proxy yaml file
  template:
    src: templates/kube-proxy.yaml
    dest: /etc/kubernetes/manifests/kube-proxy.yaml
    owner: root
    group: root
    mode: 0755

- name: Install k8s scheduler yaml file
  template:
    src: templates/kube-scheduler.yaml
    dest: /etc/kubernetes/manifests/kube-scheduler.yaml
    owner: root
    group: root
    mode: 0755

- name: Install k8s RBAC yaml file
  template:
    src: templates/kube-rbac-role-binding.yaml
    dest: /etc/kubernetes/manifests/kube-rbac-role-binding.yaml
    owner: root
    group: root
    mode: 0755

- name: Create service yaml dirs
  file:
    state: directory
    path: /home/opc/services
    owner: opc
    group: opc
    mode: 0755

- name: Prepare k8s dns yaml file
  template:
    src: templates/kube-dns.yaml
    dest: /home/opc/services/kube-dns.yaml
    owner: opc
    group: opc
    mode: 0755

- name: Prepare k8s dashboard yaml file
  template:
    src: templates/kubernetes-dashboard.yaml
    dest: /home/opc/services/kubernetes-dashboard.yaml
    owner: opc
    group: opc
    mode: 0755

- name: Create ssl dirs
  file:
    state: directory
    path: /etc/kubernetes/ssl
    owner: root
    group: root
    mode: 0755

- name: Install apiserver certs created by terraform
  template:
    src: envs/dev/apiserver.pem
    dest: /etc/kubernetes/ssl/apiserver.pem
    owner: root
    group: root
    mode: 0600

- name: Install apiserver private created by terraform
  template:
    src: envs/dev/apiserver-key.pem
    dest: /etc/kubernetes/ssl/apiserver-key.pem
    owner: root
    group: root
    mode: 0600

- name: Install ca certs created by terraform
  template:
    src: envs/dev/ca.pem
    dest: /etc/kubernetes/ssl/ca.pem
    owner: root
    group: root
    mode: 0600

- name: Install ca key created by terraform
  template:
    src: envs/dev/ca-key.pem
    dest: /etc/kubernetes/ssl/ca-key.pem
    owner: root
    group: root
    mode: 0600



- name: Environment config commands before starting kubelet
  command: "{{ item }}"
  with_items:
    - iptables -F
    - setenforce 0


- name: Install kubelet unit file
  template:
    src: templates/kubelet.service
    dest: /etc/systemd/system/kubelet.service
    owner: root
    group: root
    mode: 0644
  register: kubelet_svc_updated

- name: Restart Kubelet Service
  service:
     name: kubelet
     state: restarted
     enabled: yes
  when: kubelet_svc_updated

- name: Ensure K8s API server comes up
  health_check:
     url: http://localhost:8080/healthz
     expected_status: 200
     initial_delay: 10
     delay_between_tries: 5
     max_retries: 20

- name: Install kubernetes DNS
  command: "kubectl create -f /home/opc/services/kube-dns.yaml"
  ignore_errors: yes # this will get launched from each master, but only needs to succeed on one


- name: Install kubernetes dashboard
  command: "kubectl create -f /home/opc/services/kubernetes-dashboard.yaml"
  ignore_errors: yes # this will get launched from each master, but only needs to succeed on one


