- name: Set flannel executed fact
  set_fact: flannel_executed=False

- include: install-flannel.yml
  tags: 'flannel_install'

#- include: debug.yml
#  tags: 'flannel_debug'

- name: Set flannel executed fact
  set_fact: flannel_executed=True