---
- name: Set hostname to FQDN
  hostname:
    name: "{{ ansible_fqdn }}"

- name: Configure ntp file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf

- name: Start the ntp service
  service:
    name: ntpd
    state: started
    enabled: yes
