- name: "Create custom fact directory"
  file:
    path: "/etc/ansible/facts.d"
    state: "directory"
  check_mode: no

- name: "Create custom fact file"
  uri:
    url: http://169.254.169.254/opc/v1/instance/
    dest: /etc/ansible/facts.d/host_metadata.fact
    mode: "a+r"
    creates: /etc/ansible/facts.d/host_metadata.fact
  register: custom_facts
  check_mode: no

- name: "Re-run setup to use custom facts"
  setup: ~
  when: custom_facts.changed
  check_mode: no
  tags:
  - skip_ansible_lint
