flannel_artifact: "flannel-v{{ flannel_ver }}-linux-amd64.tar.gz"
flannel_cidr: "10.237.0.0/16"

flannel_install_dir: "/opt"
flannel_download_dir: "{{ package_download_dir }}/flannel"

flannel_network_json: {
  "Network": "{{ flannel_network_cidr }}",
  "Subnetlen": 24,
  "Backend": {
    "Type": "{{ flannel_backend }}",
    "VNI" : 1
  }
}
